version: '3' # requires Docker Compose 1.13 or later
services:
  rabbitmq:
    image: 'rabbitmq:management'
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    environment:
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - '5672:5672' # The standard AMQP protocol port
      - '15672:15672' # HTTP management UI
