version: '3'
services:
  rabbitmq:
    image: 'rabbitmq:management'
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    environment:
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - '5672:5672'
      - '15672:15672'
